// Code generated by go tool dist; DO NOT EDIT.

package main

const defaultPkgConfig = `pkg-config`

func defaultCC(goos, goarch string) string {
	switch goos + `/` + goarch {
	}
	return "/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"
}
func defaultCXX(goos, goarch string) string {
	switch goos + `/` + goarch {
	}
	return "/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++"
}
